# Generated by Django 4.2 on 2024-10-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta_data', serialize=False, to='sites.site')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='site_meta/')),
                ('social_logo', models.ImageField(upload_to='site_meta/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('x_twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('Instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
