# Generated by Django 4.2 on 2024-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemeta',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
