# Generated by Django 4.2 on 2024-10-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sitemeta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemeta',
            name='Instagram',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='facebook',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='linkedin',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='x_twitter',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
