# Generated by Django 4.2 on 2024-10-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_sitemeta_instagram_alter_sitemeta_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemeta',
            name='Instagram',
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='facebook',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='linkedin',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='sitemeta',
            name='x_twitter',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='sitemeta',
            name='instagram',
            field=models.URLField(default='#'),
        ),
    ]
