# Generated by Django 4.2 on 2024-10-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sitemeta_return_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemeta',
            name='return_address',
            field=models.TextField(default='E.D. Systems Tech Center\n3798 Oleander Ave #2\nFort Pierce, Florida 34982\nUnited States.'),
        ),
    ]
