# Generated by Django 4.2 on 2024-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmarequests',
            name='customer_name',
            field=models.CharField(help_text='Enter customer name matched with order', max_length=120),
        ),
    ]
