# Generated by Django 4.2 on 2024-10-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0002_alter_rmarequests_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RmaRequests',
        ),
    ]
