# Generated by Django 4.2 on 2024-10-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rma', '0003_delete_rmarequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmaRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter customer name matched with order', max_length=120)),
                ('email', models.EmailField(db_index=True, help_text='Email that order generated for', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Enter your phone number, it is optional.', max_length=20)),
                ('order_ref', models.CharField(db_index=True, help_text='Enter order reference number, it is mandatory.', max_length=155)),
                ('product_sku', models.CharField(help_text='Product SKU', max_length=150)),
                ('reason_for_return', models.TextField(help_text='Why you want to return the product')),
                ('rma_number', models.CharField(blank=True, db_index=True, editable=False, help_text='A Unique RMA will be generated, and will send through email!', max_length=20, unique=True)),
                ('rma_instructions', models.TextField(blank=True, help_text='Instruction that customer will receive throguh email!')),
                ('status', models.CharField(choices=[('rma_sent', 'RMA Sent'), ('pending', 'Pending'), ('product_returned', 'Product Returned')], db_index=True, default='pending', help_text='RMA status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
