# Generated by Django 4.2 on 2024-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmarequests',
            name='status',
            field=models.CharField(choices=[('rma_sent', 'RMA Sent'), ('pending', 'Pending'), ('product_received', 'Product Received')], db_index=True, default='pending', help_text='RMA status', max_length=50),
        ),
    ]
