# Generated by Django 4.2 on 2024-10-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0005_alter_rmarequests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmarequests',
            name='rma_instructions',
            field=models.TextField(blank=True, default="1. Carefully pack the item in its original packaging, including all accessories and documentation.\n2. Clearly mark the RMA number '$rma_number' on the outside of the package.\n3. Ship the package to the following address.\n4. Once the return is processed, we will notify you of the status and any further steps, if necessary.\n", help_text="Instruction that customer will receive throguh email!\nWhat you will write here will use as a middle part of mail message.\nPlease edit default value added.\nPlease ensure that there '$rma_number' variable as it is, and add in the appropiate place, which will replace by RMA number of this product. It is crutial!"),
        ),
    ]
